In [5]:
#pip install pandas
import pandas as pd

# Series — 1D labeled array:

In [6]:
import pandas as pd

# create series
s = pd.Series([10,20,30,40,50])
print(s)
# 0    10
# 1    20
# 2    30
# 3    40
# 4    50

# custom index
s = pd.Series([10,20,30], index=["a","b","c"])
print(s)
# a    10
# b    20
# c    30

# from dict
s = pd.Series({"name":"Rahul", "age":20, "city":"Pune"})
print(s)
# name    Rahul
# age        20
# city     Pune

# access
print(s["name"])   # Rahul
print(s[0])        # 10
print(s[1:3])      # slicing!

0    10
1    20
2    30
3    40
4    50
dtype: int64
a    10
b    20
c    30
dtype: int64
name    Rahul
age        20
city     Pune
dtype: object
Rahul
Rahul
age       20
city    Pune
dtype: object

C:\Users\DELL\AppData\Local\Temp\ipykernel_13524\4278293487.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])        # 10

# DataFrame — 2D labeled table:

In [7]:
# create from dict
df = pd.DataFrame({
    "name"  : ["Rahul","Priya","John","Neha"],
    "age"   : [20, 21, 19, 22],
    "marks" : [85, 92, 78, 88],
    "city"  : ["Pune","Mumbai","Delhi","Pune"]
})

print(df)
#     name  age  marks    city
# 0  Rahul   20     85    Pune
# 1  Priya   21     92  Mumbai
# 2   John   19     78   Delhi
# 3   Neha   22     88    Pune

    name  age  marks    city
0  Rahul   20     85    Pune
1  Priya   21     92  Mumbai
2   John   19     78   Delhi
3   Neha   22     88    Pune

# 2. READING DATA:

In [9]:
# # read CSV
# df = pd.read_csv("data.csv")

# # read Excel
# df = pd.read_excel("data.xlsx")

# # read JSON
# df = pd.read_json("data.json")

# # read SQL
# df = pd.read_sql(query, conn)

# # save to CSV
# df.to_csv("output.csv", index=False)

# # save to Excel
# df.to_excel("output.xlsx", index=False)

# 3. EXPLORING DATA:

In [10]:
df = pd.DataFrame({
    "name"  : ["Rahul","Priya","John","Neha","Sam"],
    "age"   : [20, 21, 19, 22, 20],
    "marks" : [85, 92, 78, 88, 65],
    "city"  : ["Pune","Mumbai","Delhi","Pune","Mumbai"]
})

# basic info
print(df.head())        # first 5 rows
print(df.tail())        # last 5 rows
print(df.head(3))       # first 3 rows
print(df.shape)         # (5, 4) rows x cols
print(df.info())        # column types
print(df.describe())    # statistics
print(df.columns)       # column names
print(df.dtypes)        # data types
print(df.isnull())      # check null values
print(df.isnull().sum())# count nulls
print(len(df))          # row count

    name  age  marks    city
0  Rahul   20     85    Pune
1  Priya   21     92  Mumbai
2   John   19     78   Delhi
3   Neha   22     88    Pune
4    Sam   20     65  Mumbai
    name  age  marks    city
0  Rahul   20     85    Pune
1  Priya   21     92  Mumbai
2   John   19     78   Delhi
3   Neha   22     88    Pune
4    Sam   20     65  Mumbai
    name  age  marks    city
0  Rahul   20     85    Pune
1  Priya   21     92  Mumbai
2   John   19     78   Delhi
(5, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
             age      marks
count   5.000000   5.000000
mean   20.400000  81.600000
std     1.140175  10.597169
min    19.000000  65.000000
25%    20.000000  78.000000
50%    20.000000  85.000000
75%    21.000000  88.000000
max    22.000000  92.000000
Index(['name', 'age', 'marks', 'city'], dtype='object')
name     object
age       int64
marks     int64
city     object
dtype: object
    name    age  marks   city
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
name     0
age      0
marks    0
city     0
dtype: int64
5

# 4. SELECTING DATA:

In [11]:
# select column
print(df["name"])           # single column
print(df[["name","marks"]]) # multiple columns

# select row by index — iloc
print(df.iloc[0])      # first row
print(df.iloc[1:3])    # rows 1 to 2
print(df.iloc[0,1])    # row 0 col 1

# select row by label — loc
print(df.loc[0])           # row 0
print(df.loc[0,"name"])    # specific cell
print(df.loc[0:2,"name":"marks"])  # range

# conditional selection
print(df[df["marks"] > 80])           # marks > 80
print(df[df["city"] == "Pune"])       # city is Pune
print(df[(df["marks"]>80) & (df["city"]=="Pune")])  # multiple!

0    Rahul
1    Priya
2     John
3     Neha
4      Sam
Name: name, dtype: object
    name  marks
0  Rahul     85
1  Priya     92
2   John     78
3   Neha     88
4    Sam     65
name     Rahul
age         20
marks       85
city      Pune
Name: 0, dtype: object
    name  age  marks    city
1  Priya   21     92  Mumbai
2   John   19     78   Delhi
20
name     Rahul
age         20
marks       85
city      Pune
Name: 0, dtype: object
Rahul
    name  age  marks
0  Rahul   20     85
1  Priya   21     92
2   John   19     78
    name  age  marks    city
0  Rahul   20     85    Pune
1  Priya   21     92  Mumbai
3   Neha   22     88    Pune
    name  age  marks  city
0  Rahul   20     85  Pune
3   Neha   22     88  Pune
    name  age  marks  city
0  Rahul   20     85  Pune
3   Neha   22     88  Pune

# 5. MODIFYING DATA:

In [12]:
# add column
df["grade"] = ["A","A","B","A","C"]

# add calculated column
df["passed"] = df["marks"] >= 40

# update column
df["marks"] = df["marks"] + 5

# rename columns
df.rename(columns={"name":"Name", "marks":"Marks"}, inplace=True)

# drop column
df.drop(columns=["grade"], inplace=True)

# drop row
df.drop(index=0, inplace=True)

# update specific value
df.loc[0,"marks"] = 95
df.at[0,"marks"]  = 95

# 6. HANDLING NULL VALUES:

In [13]:
import numpy as np

df = pd.DataFrame({
    "name"  : ["Rahul","Priya",None,"Neha"],
    "marks" : [85, None, 78, 88],
    "city"  : ["Pune","Mumbai",None,"Pune"]
})

# check nulls
print(df.isnull())
print(df.isnull().sum())

# drop nulls
df.dropna()              # drop rows with any null
df.dropna(axis=1)        # drop cols with any null

# fill nulls
df.fillna(0)             # fill with 0
df.fillna("unknown")     # fill with string
df["marks"].fillna(df["marks"].mean())  # fill with mean!

    name  marks   city
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
name     1
marks    1
city     1
dtype: int64

0    85.000000
1    83.666667
2    78.000000
3    88.000000
Name: marks, dtype: float64

# 7. GROUPBY — group and aggregate:

In [14]:
df = pd.DataFrame({
    "name"  : ["Rahul","Priya","John","Neha","Sam"],
    "city"  : ["Pune","Mumbai","Pune","Mumbai","Pune"],
    "marks" : [85, 92, 78, 88, 65]
})

# group by city
grouped = df.groupby("city")

print(grouped["marks"].mean())   # avg marks per city
print(grouped["marks"].sum())    # total marks per city
print(grouped["marks"].max())    # max marks per city
print(grouped["marks"].count())  # count per city

# multiple aggregations
print(grouped["marks"].agg(["mean","max","min","count"]))

city
Mumbai    90.0
Pune      76.0
Name: marks, dtype: float64
city
Mumbai    180
Pune      228
Name: marks, dtype: int64
city
Mumbai    92
Pune      85
Name: marks, dtype: int64
city
Mumbai    2
Pune      3
Name: marks, dtype: int64
        mean  max  min  count
city
Mumbai  90.0   92   88      2
Pune    76.0   85   65      3

# SORTING

In [15]:
# sort by column
df.sort_values("marks")                    # ascending
df.sort_values("marks", ascending=False)   # descending

# sort by multiple columns
df.sort_values(["city","marks"], ascending=[True, False])

# sort by index
df.sort_index()

    name    city  marks
0  Rahul    Pune     85
1  Priya  Mumbai     92
2   John    Pune     78
3   Neha  Mumbai     88
4    Sam    Pune     65

# 9. MERGING & JOINING:

In [16]:
df1 = pd.DataFrame({
    "id"  : [1,2,3],
    "name": ["Rahul","Priya","John"]
})

df2 = pd.DataFrame({
    "id"   : [1,2,4],
    "marks": [85,92,78]
})

# merge — like SQL JOIN
pd.merge(df1, df2, on="id")              # inner join
pd.merge(df1, df2, on="id", how="left")  # left join
pd.merge(df1, df2, on="id", how="right") # right join
pd.merge(df1, df2, on="id", how="outer") # outer join

# concat — stack dataframes
pd.concat([df1, df2])          # vertical
pd.concat([df1, df2], axis=1)  # horizontal

   id   name  id  marks
0   1  Rahul   1     85
1   2  Priya   2     92
2   3   John   4     78

# 10. APPLY & MAP:

In [17]:
# apply function to column
df["marks"] = df["marks"].apply(lambda x: x*1.1)

# apply to entire dataframe
df.apply(lambda x: x.max())

# map values
df["grade"] = df["marks"].map({
    85:"A", 92:"A", 78:"B", 88:"A", 65:"C"
})

# string operations
df["name"].str.upper()
df["name"].str.lower()
df["name"].str.len()
df["name"].str.contains("R")

0     True
1    False
2    False
3    False
4    False
Name: name, dtype: bool

# 11. PIVOT TABLE:

In [19]:
df = pd.DataFrame({
    "name"  : ["Rahul","Priya","Rahul","Priya"],
    "subject":["Math","Math","Science","Science"],
    "marks" : [85, 92, 78, 88]
})

pivot = pd.pivot_table(
    df,
    values ="marks",
    index  ="name",
    columns="subject",
    aggfunc="mean"
)
print(pivot)

subject  Math  Science
name
Priya    92.0     88.0
Rahul    85.0     78.0