In [92]:
import pandas as pd
import numpy as np

# 1

In [93]:
s1 = pd.Series([10,20,30,40,50])
s2 = pd.Series([10,10,10,10,10])
print(s1)
print(s2)
print("Addtion : \n",s1+s1)
print("SUB: \n", s1-s2)
print("Mul : \n", s1*s2)

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10
1    10
2    10
3    10
4    10
dtype: int64
Addtion :
 0     20
1     40
2     60
3     80
4    100
dtype: int64
SUB:
 0     0
1    10
2    20
3    30
4    40
dtype: int64
Mul :
 0    100
1    200
2    300
3    400
4    500
dtype: int64

# 2

In [94]:
d = {"name":"Rahul", "age":20, "city":"Pune"}
s = pd.Series(d)
print("Series Using dict: \n",s)

Series Using dict:
 name    Rahul
age        20
city     Pune
dtype: object

# 3

In [95]:
arr = np.array([1,2,3,4,5])
s = pd.Series(arr,index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int32

# 4

In [96]:
arr1 = np.arange(0,12)

s = pd.Series(arr1)

print(s)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
dtype: int32

In [97]:
print(s.iloc[:6])

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

# 5

In [98]:
series = pd.Series([10,20,30,40,50])
print(series.describe())

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

# 6

In [99]:
d={'Name':['Sonu','Raja','Ketki','Rupa','Radha','Reshma','Keshav','Narendra','Rani','Kittu'],
    'marks':[12.5, 9,16.5,np.nan,9,20,14.5,np.nan,8,19],
    'attempts':[1,3,2,3,2,3,1,1,2,1],
    'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(d,index=labels)

print(df)

       Name  marks  attempts qualify
a      Sonu   12.5         1     yes
b      Raja    9.0         3      no
c     Ketki   16.5         2     yes
d      Rupa    NaN         3      no
e     Radha    9.0         2      no
f    Reshma   20.0         3     yes
g    Keshav   14.5         1     yes
h  Narendra    NaN         1      no
i      Rani    8.0         2      no
j     Kittu   19.0         1     yes

# 7

In [100]:
df.describe()

           marks   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

# 8

In [101]:
print(df.head(3))

    Name  marks  attempts qualify
a   Sonu   12.5         1     yes
b   Raja    9.0         3      no
c  Ketki   16.5         2     yes

# 9

In [102]:
name_marks_df = df[["Name","marks"]]
print(name_marks_df)

       Name  marks
a      Sonu   12.5
b      Raja    9.0
c     Ketki   16.5
d      Rupa    NaN
e     Radha    9.0
f    Reshma   20.0
g    Keshav   14.5
h  Narendra    NaN
i      Rani    8.0
j     Kittu   19.0

# 11

In [103]:
i_df = df.iloc[[1, 3, 5, 6]][["Name", "marks"]]
print(i_df)

     Name  marks
b    Raja    9.0
d    Rupa    NaN
f  Reshma   20.0
g  Keshav   14.5

# 12

In [104]:
df[df['attempts']>2]

     Name  marks  attempts qualify
b    Raja    9.0         3      no
d    Rupa    NaN         3      no
f  Reshma   20.0         3     yes

# 13

In [105]:
df.shape

(10, 4)

# 14

In [106]:
df[(df['marks'] > 15) & (df['marks'] < 20)]

    Name  marks  attempts qualify
c  Ketki   16.5         2     yes
j  Kittu   19.0         1     yes

# 15

In [112]:
df[(df['attempts'] < 2) & (df['marks'] > 15)]

    Name  marks  attempts qualify
j  Kittu   19.0         1     yes

# 16

In [108]:
df['marks'].sum()

108.5

# 17

In [109]:
df['marks'].mean()

13.5625

# 18

In [111]:
df.sort_values("Name", ascending=True)

       Name  marks  attempts qualify
g    Keshav   14.5         1     yes
c     Ketki   16.5         2     yes
j     Kittu   19.0         1     yes
h  Narendra    NaN         1      no
e     Radha    9.0         2      no
b      Raja    9.0         3      no
i      Rani    8.0         2      no
f    Reshma   20.0         3     yes
d      Rupa    NaN         3      no
a      Sonu   12.5         1     yes

# 19

In [113]:
df['new_column'] = [1,2,3,4,5,6,7,8,9,10]
df

       Name  marks  attempts qualify  new_column
a      Sonu   12.5         1     yes           1
b      Raja    9.0         3      no           2
c     Ketki   16.5         2     yes           3
d      Rupa    NaN         3      no           4
e     Radha    9.0         2      no           5
f    Reshma   20.0         3     yes           6
g    Keshav   14.5         1     yes           7
h  Narendra    NaN         1      no           8
i      Rani    8.0         2      no           9
j     Kittu   19.0         1     yes          10

# 20

In [116]:
data = {'name':['Alice','Bob','Charlie'],
        'age':[25,30,35],
        'Gender':['female','male','female'],
        'city':['new york','pune','new york']}

df = pd.DataFrame(data)
print(df)

      name  age  Gender      city
0    Alice   25  female  new york
1      Bob   30    male      pune
2  Charlie   35  female  new york

In [117]:
df.shape

(3, 4)

In [118]:
df.columns

Index(['name', 'age', 'Gender', 'city'], dtype='object')

In [120]:
df['age'].mean()

30.0

In [128]:
[df[df['city'] == 'new york']]

[      name  age  Gender      city
 0    Alice   25  female  new york
 2  Charlie   35  female  new york]

In [131]:
df[df['city'] == 'new york'].count()

name      2
age       2
Gender    2
city      2
dtype: int64

In [130]:
len(df[df['city'] == 'new york'])

2

In [124]:
df[(df['age'] > 30)].sort_values('name',ascending=True)

      name  age  Gender      city
2  Charlie   35  female  new york